server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  thymeleaf:
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    #内容类别,可不用配置
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/
  redis:
    host: localhost
    port: 6379
    password: 199917
    database: 0
  cache:
    type: redis


mybatis:
  #实现Mapper接口与xml文件的绑定
  mapper-locations: classpath:mappers/*Mapper.xml
  #注册实体类
  type-aliases-package: com.example.demo.model
  #设置配置的日志输出信息(看sql)
  configuration:
    #关闭日志
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


imageFilePath: D://Codes/Springboot-learning/src/main/resources/static/movieImage/
